language: ruby

rvm:
  - 2.1.0

bundler_args: --jobs 7 --without kitchen_vagrant --without development

branches:
  only:
    - master

before_install:
  - export USE_SYSTEM_GECODE=1
  - sudo apt-get -y install libgecode-dev

script: bundle exec rake travis:ci

notifications:
  hipchat:
    on_change: true
    on_failure: true
    on_success: false
    on_pull_requests: false
    rooms:
      # Build Statuses
      - secure: fk4NTplcjE097Oan2HgZc+Lxx8X9k2QDolwBKZMDNrreFImBgw6HJBwHUv6Hfay2xh7Y720iNFeTTN3Ep0/M4YgmBrwhry3jSMN8TX7SAOGPCC8zIB0ELGGAyQKxDjwwsA18KTbuDkV5yboiUzvY86G5bWT8vfWEd1ljTEnIazQ=
      # Release Engineering
      - secure: X35KY6kImjVyYiT9gOlRJd26MKh5KQFwxcQm3fF9Y+pnB1v7uB3w6+jzoxhvPN5O2US3xGQsaJOSAB1uhZh+FZOKfZ/ewyXVUcTXrUTC9Mjofd3n33xD68qoI22mntEQilugvC+OPhq9uWyX0OlRhnnT+J56Vq7feSI4ez9e9Og=
